### PR TITLE
Feature/iso din bringup on comemso

### PR DESCRIPTION
**Pull request by martinbachmanndesignwerk**
We have successfully charged iso15118-2 and din on our comemso multimobile protocol tester. I've unittests with test json from the charging session to verify message creation works.

### CODE REVIEW

**Comment by tropxy** [comment]
Hi @martinbachmanndesignwerk ! thanks for this contribution. I quickly went through it and looks good; I want to give it a deeper look, but before that could you rebase your branch against latest master and solve the conflicts?

thanks!

**Comment by martinbachmanndesignwerk** [comment]
> Hi @martinbachmanndesignwerk ! thanks for this contribution. I quickly went through it and looks good; I want to give it a deeper look, but before that could you rebase your branch against latest master and solve the conflicts?
> 
> thanks!

Done... Ready for review... :-)

**Review by tropxy — CHANGES_REQUESTED** [review]
Hi it looks good just needs rebasing again

**Review by tropxy — APPROVED** [review]

**Comment by tropxy** [comment]
I rebased and looks good, so I am merging it. Thanks @martinbachmanndesignwerk!!

**Pull request merged**
