### PR TITLE
EVCC enable charging and fix for DIN EVSE initiated stop

### LINKED ISSUE #356: evse_notification  incorrectly used to detect shutdown request from EVSE in dinspec
Hi,

For din spec on the EV side, EVSE initated shutdown is checked like this:

`

    if dc_evse_status.evse_notification == EVSENotification.STOP_CHARGING:
        logger.debug("EVSE Notification received requesting to stop charging.")
        await self.stop_charging()
`

DIN spec states however that evse_notification should always be set to None.
What you actually want to check is DCEVSEStatusCode.

There for if the EVSE wants to initate shutdown it currently will not work

### PR DESCRIPTION
**Pull request by heavyweight87**
Fixes #356 and #264 

- Added enable_charging to evcc controller interface. This gives the EVCC the opertunity to go to state C (or B)
- Fixed an issue where the wrong flag was checked when receiving current demand response for EVSE initiated shutdown (DIN only)

### CODE REVIEW

**Comment by shalinnijel2** [comment]
@heavyweight87 - thank you for opening this PR. :). Just noticed one thing - calling enable_charging(True) in -20 was missed.
Call enable_charging(True) just above the below lines if charge progress is set to START to cater for both AC and DC?
https://github.com/SwitchEV/iso15118/blob/b3f3a6233c4cf1c3d434c7926f4056f4a271f107/iso15118/evcc/states/iso15118_20_states.py#L858
https://github.com/SwitchEV/iso15118/blob/b3f3a6233c4cf1c3d434c7926f4056f4a271f107/iso15118/evcc/states/iso15118_20_states.py#L1579

**Comment by shalinnijel2** [comment]
The following commands would help identify any linting issues:
```
make flake8
make black
make reformat
```

**Comment by heavyweight87** [comment]
> @heavyweight87 - thank you for opening this PR. :). Just noticed one thing - calling enable_charging(True) in -20 was missed. Call enable_charging(True) just above the below lines if charge progress is set to START to cater for both AC and DC?
> 
> https://github.com/SwitchEV/iso15118/blob/b3f3a6233c4cf1c3d434c7926f4056f4a271f107/iso15118/evcc/states/iso15118_20_states.py#L858
> 
> 
> https://github.com/SwitchEV/iso15118/blob/b3f3a6233c4cf1c3d434c7926f4056f4a271f107/iso15118/evcc/states/iso15118_20_states.py#L1579

Ah how did I miss that! Thanks - added and also fixed the linter problem!

**Comment by heavyweight87** [comment]
The test was using the old method of stopping charging - now fixed and hopefully should pass the test.

**Review by shalinnijel2 — APPROVED** [review]
LGTM.

**Comment by shalinnijel2** [comment]
I'm merging this to master. I'll close the other two related tickets as well. Feel free to reopen if there is more to add.

**Pull request merged**
