### PR TITLE
ScheduleExchangeRes parsing fix

### PR DESCRIPTION
**Pull request by heavyweight87**
- ScheduleExchangeResponse parser was checking that either absolute or price levels were set, which according to the standard both are optional in this case 
- Fixed an issue where charging was not disabled when the session stopped abruptly (due to parsing errors etc)
- Fixed an issue with charging_enabled not being called in the correct place for ISO-20
- Fixed power delivery request not checking which service is currently being used for ISO-20
- Fixed an issue with BPT power profiles causing an exception for ISO-20

### CODE REVIEW

**Comment by shalinnijel2** [comment]
Thanks for this @heavyweight87 . I had to double check this in the -20 user group before approving. I see this issue is clarified here: https://iso15118.elaad.io/pt2/15118-20/user-group/-/issues/27

**Review by shalinnijel2 — APPROVED** [review]

**Comment by heavyweight87** [comment]
Thanks! I will close the issue

**Comment by heavyweight87** [comment]
Accidently closed the MR I thougt it was already merged :)

**Comment by heavyweight87** [comment]
Hi,
Any chances of merging this?

**Comment by shalinnijel2** [comment]
Done - just got back from holiday today. Thank you for this @heavyweight87 . :).

**Comment by heavyweight87** [comment]
Thanks! Sorry to rush you... hope you had fun :)

**Pull request merged**
